services:
  campuseats:
    image: campuseats
    build:
      context: .
      dockerfile: CampusEats/Dockerfile
    ports:
      - "8080:8080"

  campuseats.tests:
    image: campuseats.tests
    build:
      context: .
      dockerfile: CampusEats.Tests/Dockerfile

  campuseatsui:
    image: campuseatsui
    build:
      context: .
      dockerfile: CampusEatsUI/Dockerfile
    ports:
      - "8081:80"

  campuseatsui.tests:
    image: campuseatsui.tests
    build:
      context: .
      dockerfile: CampusEatsUi.Tests/Dockerfile

