services:
  campuseats:
    image: campuseats
    build:
      context: .
      dockerfile: CampusEats/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - Stripe__WebhookSecret=${STRIPE_WEBHOOK_SECRET}

  campuseatsui-build:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    working_dir: /src
    volumes:
      - .:/src
      - build-output:/output
    command: /bin/sh -c "dotnet publish CampusEatsUI/CampusEatsUI.csproj -c Release -o /tmp/build && rm -rf /output/* && cp -r /tmp/build/wwwroot/. /output"

  campuseatsui-serve:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - build-output:/usr/share/nginx/html
      - ./CampusEatsUI/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      campuseats:
        condition: service_started
      campuseatsui-build:
        condition: service_completed_successfully


  stripe-cli:
    image: stripe/stripe-cli
    command: listen --forward-to http://localhost:5001/api/webhooks/stripe --api-key ${STRIPE_SECRET_KEY}
    depends_on:
      - campuseats

volumes:
  build-output:
